# this sets the logger level (true = info, false = debug)
production: true

operator_address: 0x860B6912C2d0337ef05bbC89b0C2CB6CbAEAB4A5

# EigenLayer Slasher contract address

# This is the address of the contracts which are deployed in the anvil saved state
# The saved eigenlayer state is located in tests/anvil/credible_squaring_avs_deployment_output.json
# TODO(samlaf): automate updating these addresses when we deploy new contracts
avs_registry_coordinator_address: 0x10A95e48a51dD3c2b0d37aF4d70b0AC47e755430 #registryCoordinator
operator_state_retriever_address: 0x4D90e0c42F92149FA005d27139f2657CdcC3A850 #operatorStateRetriver

# ETH RPC URL
eth_rpc_url: http://geth:8545
eth_ws_url: ws://geth:8546

# If you running this using eigenlayer CLI and the provided AVS packaging structure,
# this should be /operator_keys/ecdsa_key.json as the host path will be asked while running
#
# If you are running locally using go run main.go, this should be full path to your local ecdsa key file
ecdsa_private_key_store_path: tests/keys/test.ecdsa.key.json

# If you running this using eigenlayer CLI and the provided AVS packaging structure,
# this should be /operator_keys/bls_key.json as the host path will be asked while running
#
# We are using bn254 curve for bls keys
#
# If you are running locally using go run main.go, this should be full path to your local bls key file
bls_private_key_store_path: tests/keys/test.bls.key.json

# address which the aggregator listens on for operator signed messages
aggregator_server_ip_port_address: aggregator:8090

# avs node spec compliance https://eigen.nethermind.io/docs/spec/intro
eigen_metrics_ip_port_address: 0.0.0.0:9090
enable_metrics: true
node_api_ip_port_address: 0.0.0.0:9010
enable_node_api: true

register_operator_on_startup: true
# address of token to deposit tokens into when registering on startup
# addresses.erc20MockStrategy in tests/anvil/credible_squaring_avs_deployment_output.json
token_strategy_addr: 0x3a63ac6a25cb4ed2c85A8A986F4032003e5dC734
